apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopsdep
  name: devopsdep
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsdep
  template:
    metadata:
      labels:
        app: devopsdep
    spec:
      containers:
      - image: yogeshraheja/devopspython:v1
        name: devopspython
